document.addEventListener('DOMContentLoaded', async () => {
  const user = await AttendanceApp.requireSession(); if (!user || !['HR', 'ADMIN'].includes(user.role)) return;
  const page = document.body.dataset.page; const state = document.querySelector('[data-state]'); const table = document.querySelector('[data-body]'); let currentPage = 1; let departments = [];
  const date = (value) => value ? value.slice(0, 10) : '—';
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const populateOptions = (selector, values, label) => document.querySelectorAll(selector).forEach((select) => values.forEach((item) => { const option = document.createElement('option'); option.value = item._id; option.textContent = label(item); select.append(option); }));
  try { const [deptResult, employeeResult] = await Promise.all([AttendanceApp.apiRequest('/departments'), AttendanceApp.apiRequest('/employees?limit=100')]); departments = deptResult.data.departments; populateOptions('[data-department-options]', departments, (item) => item.name); populateOptions('[data-employee-options]', employeeResult.data.employees, (item) => `${item.name} (${item.employeeId || item.email})`); } catch (error) { state.textContent = error.message; }
  const params = () => { const result = new URLSearchParams({ page: currentPage, limit: 20 }); document.querySelectorAll('[data-filter]').forEach((input) => { if (input.value) result.set(input.name, input.value); }); return result; };
  const addCell = (row, value, className) => { const cell = document.createElement('td'); cell.textContent = value; if (className) cell.className = className; row.append(cell); };
  const editEmployee = (item) => {
    const modal = document.createElement('div'); modal.className = 'modal open';
    const options = departments.map((department) => `<option value="${escapeHtml(department._id)}" ${item.department?._id === department._id ? 'selected' : ''}>${escapeHtml(department.name)}</option>`).join('');
    modal.innerHTML = `<div class="modal-panel"><h2>Edit employee</h2><form class="form-grid"><div class="form-group"><label>Name</label><input name="name" required value="${escapeHtml(item.name)}" /></div><div class="form-group"><label>Email</label><input name="email" type="email" required value="${escapeHtml(item.email)}" /></div><div class="form-group"><label>Department</label><select name="department"><option value="">Unassigned</option>${options}</select></div><div class="form-group"><label>Role</label><select name="role"><option ${item.role === 'EMPLOYEE' ? 'selected' : ''}>EMPLOYEE</option><option ${item.role === 'HR' ? 'selected' : ''}>HR</option>${user.role === 'ADMIN' ? `<option ${item.role === 'ADMIN' ? 'selected' : ''}>ADMIN</option>` : ''}</select></div><div class="actions"><button class="primary" type="submit">Save changes</button><button class="secondary" type="button" data-close>Cancel</button></div></form></div>`;
    document.body.append(modal); modal.querySelector('[data-close]').onclick = () => modal.remove(); modal.addEventListener('click', (event) => { if (event.target === modal) modal.remove(); });
    modal.querySelector('form').onsubmit = async (event) => { event.preventDefault(); const button = event.currentTarget.querySelector('[type=submit]'); button.disabled = true; try { await AttendanceApp.apiRequest(`/employees/${item._id}`, { method: 'PUT', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); AttendanceApp.toast('Employee updated.', 'success'); modal.remove(); load(); } catch (error) { AttendanceApp.toast(error.message, 'error'); button.disabled = false; } };
  };
  const loadEmployees = async () => { const result = await AttendanceApp.apiRequest(`/employees?${params()}`); table.replaceChildren(); result.data.employees.forEach((item) => { const row = document.createElement('tr'); [item.employeeId || '—', item.name, item.email, item.department?.name || 'Unassigned', item.role, item.isActive ? 'Active' : 'Inactive'].forEach((value) => addCell(row, value)); const actions = document.createElement('td'); actions.className = 'table-actions'; const edit = document.createElement('button'); edit.className = 'secondary'; edit.textContent = 'Edit'; edit.onclick = () => editEmployee(item); const toggle = document.createElement('button'); toggle.className = item.isActive ? 'danger' : 'primary'; toggle.textContent = item.isActive ? 'Deactivate' : 'Activate'; toggle.onclick = async () => { if (!window.confirm(`${toggle.textContent} ${item.name}?`)) return; try { await AttendanceApp.apiRequest(`/employees/${item._id}/status`, { method: 'PATCH', body: JSON.stringify({ isActive: !item.isActive }) }); AttendanceApp.toast(`Employee ${item.isActive ? 'deactivated' : 'activated'}.`, 'success'); load(); } catch (error) { AttendanceApp.toast(error.message, 'error'); } }; actions.append(edit, toggle); row.append(actions); table.append(row); }); const pagination = document.querySelector('[data-pagination]'); if (pagination) { pagination.replaceChildren(); const info = document.createElement('span'); info.textContent = `Page ${result.data.pagination.page} of ${Math.max(result.data.pagination.totalPages, 1)}`; const previous = document.createElement('button'); previous.className = 'secondary'; previous.textContent = 'Previous'; previous.disabled = currentPage <= 1; previous.onclick = () => { currentPage -= 1; load(); }; const next = document.createElement('button'); next.className = 'secondary'; next.textContent = 'Next'; next.disabled = currentPage >= result.data.pagination.totalPages; next.onclick = () => { currentPage += 1; load(); }; pagination.append(previous, info, next); } state.textContent = result.data.employees.length ? '' : 'No employees found.'; };
  const loadAttendance = async () => { const result = await AttendanceApp.apiRequest(`/attendance/management?${params()}`); table.replaceChildren(); result.data.attendance.forEach((item) => { const employee = item.employee || {}; const row = document.createElement('tr'); [date(item.date), employee.name || '—', employee.employeeId || '—', employee.department?.name || 'Unassigned', item.checkIn ? new Date(item.checkIn).toLocaleTimeString() : '—', item.checkOut ? new Date(item.checkOut).toLocaleTimeString() : '—', item.workingMinutes ? `${Math.floor(item.workingMinutes / 60)}h ${item.workingMinutes % 60}m` : '—', item.lateMinutes || 0].forEach((value) => addCell(row, value)); addCell(row, item.status, `badge ${item.status.toLowerCase().replace('_', '-')}`); table.append(row); }); state.textContent = result.data.attendance.length ? '' : 'No attendance found.'; };
  const loadLeaves = async () => { const result = await AttendanceApp.apiRequest(`/leaves?${params()}`); table.replaceChildren(); result.data.leaves.forEach((leave) => { const row = document.createElement('tr'); [leave.employee?.name || '—', leave.leaveType, date(leave.startDate), date(leave.endDate), leave.leaveDays, leave.reason || '—'].forEach((value) => addCell(row, value)); addCell(row, leave.status, `badge ${leave.status.toLowerCase()}`); addCell(row, leave.reviewComment || '—'); addCell(row, leave.reviewer?.name || '—'); addCell(row, leave.reviewedAt ? new Date(leave.reviewedAt).toLocaleString() : '—'); const actions = document.createElement('td'); actions.className = 'table-actions'; if (leave.status === 'PENDING') { const approve = document.createElement('button'); approve.className = 'primary'; approve.textContent = 'Approve'; approve.onclick = async () => { try { await AttendanceApp.apiRequest(`/leaves/${leave._id}/approve`, { method: 'PUT' }); AttendanceApp.toast('Leave approved.', 'success'); load(); } catch (error) { AttendanceApp.toast(error.message, 'error'); } }; const reject = document.createElement('button'); reject.className = 'danger'; reject.textContent = 'Reject'; reject.onclick = async () => { const reviewComment = window.prompt('Rejection comment (at least 3 characters)'); if (!reviewComment) return; try { await AttendanceApp.apiRequest(`/leaves/${leave._id}/reject`, { method: 'PUT', body: JSON.stringify({ reviewComment }) }); AttendanceApp.toast('Leave rejected.', 'success'); load(); } catch (error) { AttendanceApp.toast(error.message, 'error'); } }; actions.append(approve, reject); } row.append(actions); table.append(row); }); state.textContent = result.data.leaves.length ? '' : 'No leave requests found.'; };
  const loadCorrections = async () => { const result = await AttendanceApp.apiRequest('/corrections/pending'); table.replaceChildren(); result.data.corrections.forEach((item) => { const row = document.createElement('tr'); const employee = item.employee || {}; [employee.name || '—', date(item.attendance?.date), item.requestedCheckIn || '—', item.requestedCheckOut || '—', item.reason, item.status].forEach((value) => addCell(row, value)); const actions = document.createElement('td'); actions.className = 'table-actions'; const review = async (decision) => { const reviewComment = window.prompt(`${decision === 'approve' ? 'Approval' : 'Rejection'} comment (optional for approval)`); if (decision === 'reject' && !reviewComment) return; try { await AttendanceApp.apiRequest(`/corrections/${item._id}/${decision}`, { method: 'PUT', body: JSON.stringify({ reviewComment }) }); AttendanceApp.toast(`Correction ${decision}d.`, 'success'); load(); } catch (error) { AttendanceApp.toast(error.message, 'error'); } }; ['approve', 'reject'].forEach((decision) => { const button = document.createElement('button'); button.className = decision === 'approve' ? 'primary' : 'danger'; button.textContent = decision[0].toUpperCase() + decision.slice(1); button.onclick = () => review(decision); actions.append(button); }); row.append(actions); table.append(row); }); state.textContent = result.data.corrections.length ? '' : 'No pending corrections.'; };
  const load = async () => { state.textContent = 'Loading…'; try { if (page === 'employees') await loadEmployees(); else if (page === 'attendance-management') await loadAttendance(); else if (page === 'corrections') await loadCorrections(); else await loadLeaves(); } catch (error) { state.textContent = error.message; } };
  document.querySelector('[data-filters]')?.addEventListener('submit', (event) => { event.preventDefault(); currentPage = 1; load(); }); document.querySelector('[data-refresh]')?.addEventListener('click', load);
  document.querySelector('[data-create-employee]')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button'); button.disabled = true; try { await AttendanceApp.apiRequest('/employees', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); form.reset(); AttendanceApp.toast('Employee created.', 'success'); currentPage = 1; await load(); } catch (error) { AttendanceApp.toast(error.message, 'error'); } finally { button.disabled = false; } }); await load();
});
