document.addEventListener('DOMContentLoaded', async () => {
  const user = await AttendanceApp.requireSession(); if (!user) return;
  const form = document.querySelector('[data-leave-form]'); const table = document.querySelector('[data-leaves-body]'); const state = document.querySelector('[data-state]');
  Object.entries(user.leaveBalances || {}).forEach(([type, value]) => { const node = document.querySelector(`[data-balance="${type}"]`); if (node) node.textContent = value; });
  const load = async () => { state.textContent = 'Loading leave history...'; try { const result = await AttendanceApp.apiRequest('/leaves/my-leaves?limit=100'); table.replaceChildren(); result.data.leaves.forEach((leave) => { const row = document.createElement('tr'); [leave.leaveType, leave.startDate.slice(0, 10), leave.endDate.slice(0, 10), leave.leaveDays, leave.reason, leave.status].forEach((value, index) => { const cell = document.createElement('td'); cell.textContent = value; if (index === 5) cell.className = `badge ${value.toLowerCase()}`; row.append(cell); }); if (leave.status === 'PENDING') { const cell = document.createElement('td'); const button = document.createElement('button'); button.className = 'danger'; button.textContent = 'Cancel'; button.addEventListener('click', async () => { if (!window.confirm('Cancel this pending request?')) return; try { await AttendanceApp.apiRequest(`/leaves/${leave._id}/cancel`, { method: 'DELETE' }); AttendanceApp.toast('Leave request cancelled.', 'success'); load(); } catch (error) { AttendanceApp.toast(error.message, 'error'); } }); cell.append(button); row.append(cell); } table.append(row); }); state.textContent = result.data.leaves.length ? '' : 'No leave requests yet.'; } catch (error) { state.textContent = error.message; } };
  const updateCalculatedDays = () => { const start = new Date(`${form.startDate.value}T00:00:00Z`); const end = new Date(`${form.endDate.value}T00:00:00Z`); const days = form.startDate.value && form.endDate.value && end >= start ? Math.floor((end - start) / 86400000) + 1 : null; document.querySelector('[data-calculated-days]').textContent = days ? `${days} day${days === 1 ? '' : 's'}` : '—'; };
  form.startDate.addEventListener('change', updateCalculatedDays); form.endDate.addEventListener('change', updateCalculatedDays);
  form.addEventListener('submit', async (event) => { event.preventDefault(); if (!form.reportValidity() || new Date(form.startDate.value) > new Date(form.endDate.value)) { AttendanceApp.toast('Please check the leave dates.', 'error'); return; } const button = form.querySelector('button'); button.disabled = true; try { const result = await AttendanceApp.apiRequest('/leaves', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); document.querySelector('[data-returned-days]').textContent = `${result.data.leave.leaveDays} days`; AttendanceApp.toast('Leave request submitted.', 'success'); form.reset(); updateCalculatedDays(); load(); } catch (error) { AttendanceApp.toast(error.message, 'error'); } finally { button.disabled = false; } });
  await load();
});
