const createCsv = (rows) => rows.map((row) => row.map((value) => { const text = String(value ?? ''); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }).join(',')).join('\n');
const attendanceCsv = (attendance = []) => createCsv([['Date', 'Employee', 'Employee ID', 'Department', 'Check-in', 'Check-out', 'Working duration', 'Late minutes', 'Overtime', 'Status'], ...attendance.map((item) => [item.date, item.employee?.name, item.employee?.employeeId, item.employee?.department?.name, item.checkIn, item.checkOut, item.workingMinutes, item.lateMinutes, item.overtimeMinutes, item.status])]);
const leaveCsv = (leaves = []) => createCsv([['Employee', 'Employee ID', 'Department', 'Leave type', 'Start date', 'End date', 'Days', 'Status'], ...leaves.map((item) => [item.employee?.name, item.employee?.employeeId, item.employee?.department?.name, item.leaveType, item.startDate, item.endDate, item.leaveDays, item.status])]);
window.AttendanceReports = { attendanceCsv, createCsv, leaveCsv };

document.addEventListener('DOMContentLoaded', async () => {
  const user = await AttendanceApp.requireSession(); if (!user || !['HR', 'ADMIN'].includes(user.role)) return;
  const form = document.querySelector('[data-filters]'); const attendanceBody = document.querySelector('[data-attendance-body]'); const leaveBody = document.querySelector('[data-leave-body]'); const state = document.querySelector('[data-state]'); let report = { attendance: [], leaves: [] };
  const employeeField = document.createElement('select'); employeeField.name = 'employee'; employeeField.innerHTML = '<option value="">All employees</option>'; const departmentField = document.createElement('select'); departmentField.name = 'department'; departmentField.innerHTML = '<option value="">All departments</option>'; [employeeField, departmentField].forEach((field) => { const group = document.createElement('div'); group.className = 'form-group'; const label = document.createElement('label'); label.textContent = field.name === 'employee' ? 'Employee' : 'Department'; group.append(label, field); form.insertBefore(group, form.lastElementChild); });
  try { const sources = await Promise.all([AttendanceApp.apiRequest('/employees?limit=100'), AttendanceApp.apiRequest('/departments')]); sources[0].data.employees.forEach((item) => { const option = document.createElement('option'); option.value = item._id; option.textContent = `${item.name} (${item.employeeId || item.email})`; employeeField.append(option); }); sources[1].data.departments.forEach((item) => { const option = document.createElement('option'); option.value = item._id; option.textContent = item.name; departmentField.append(option); }); } catch (error) { state.textContent = error.message; return; }
  const load = async () => { state.textContent = 'Loading report...'; try { const params = new URLSearchParams(); form.querySelectorAll('input, select').forEach((field) => { if (field.value) params.set(field.name, field.value); }); report = (await AttendanceApp.apiRequest(`/reports/attendance?${params}`)).data; attendanceBody.replaceChildren(); leaveBody.replaceChildren(); report.attendance.forEach((item) => { const row = document.createElement('tr'); const employee = item.employee || {}; [item.date.slice(0, 10), employee.name || '—', employee.employeeId || '—', employee.department?.name || 'Unassigned', item.checkIn ? new Date(item.checkIn).toLocaleTimeString() : '—', item.checkOut ? new Date(item.checkOut).toLocaleTimeString() : '—', item.workingMinutes ? `${Math.floor(item.workingMinutes / 60)}h ${item.workingMinutes % 60}m` : '—', item.lateMinutes, item.overtimeMinutes, item.status].forEach((value) => { const cell = document.createElement('td'); cell.textContent = value; row.append(cell); }); attendanceBody.append(row); }); report.leaves.forEach((item) => { const row = document.createElement('tr'); [item.employee?.name || '—', item.employee?.employeeId || '—', item.employee?.department?.name || 'Unassigned', item.leaveType, item.startDate.slice(0, 10), item.endDate.slice(0, 10), item.leaveDays, item.status].forEach((value) => { const cell = document.createElement('td'); cell.textContent = value; row.append(cell); }); leaveBody.append(row); }); state.textContent = report.attendance.length || report.leaves.length ? '' : 'No report data for these filters.'; } catch (error) { state.textContent = error.message; } };
  const download = (name, content) => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' })); link.download = name; link.click(); URL.revokeObjectURL(link.href); };
  document.querySelector('[data-export-attendance]').onclick = () => download('attendance-report.csv', attendanceCsv(report.attendance)); document.querySelector('[data-export-leave]').onclick = () => download('leave-report.csv', leaveCsv(report.leaves)); form.onsubmit = (event) => { event.preventDefault(); load(); }; await load();
});
